baseURL = "https://kaohsiung.gcpug.tw/"
languageCode = "tw"
defaultContentLanguage = "tw"
title = "GDG Cloud Kaohsiung"

# Theme
theme = "devfest-theme-hugo"

# Params

enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

googleAnalytics = ""

[params]
    title = "GDG Cloud Kaohsiung"
    date = "2019-10-03"
    description = "Google Develop Group Cloud Kaohsiung a.k.a. GDG Cloud Kaohsiung 為 GDG Cloud 高雄分支，主要為 GCP 相關應用技術交流，希望可以聚集南台灣對於 GCP 有興趣的使用者們加入，也會不定期舉辦聚會活動，想要了解 GDG Cloud Kaohsiung 都在聊些什麼，那就加入我們吧！"
    images = ["/images/social-share.png"]
    email = "gcpug.kh@gmail.com"
    keywords = "event, gdg, gdg cloud, gde, google, programming, android, chrome, developers, web, cloud, androiddev"
    copyright = "Copyright © 2019, GDG Cloud Kaohsiung; all rights reserved."
#    cfpUrl = ""
#    subscriptionUrl = ""
    appleTouchIcon = "/apple-touch-icon.png"
    favicon32 = "/favicon.png"
    favicon16 = "/favicon.png"
    manifest = ""
    safariPinnedTab = "/safari-pinned-tab.png"
    themeColor = "#4285f4"

[params.logos]
    jumbo = "/images/logos/logo_lockup_vertical_white_color.png"
    header = "/images/logos/logo_lockup_horizontal_white.png"
    footer = "/images/logos/logo_lockup_horizontal_color.png"

#[menu]
#[[menu.main]]
#    identifier = "jobs"
#    name = "Jobs"
#    url = "https://jobs.devfesttoulouse.fr/"
#    weight = 200
#    external = true

[languages]
[languages.tw]
    weight = 1
    languageName = "tw"
#
#[languages.fr]
#    weight = 2
#    languageName = "fr"

#[languages.fr.params]
#    description = "Le DevFest, ou 'Developers Festival', est une conférence technique destinée aux développeurs. Elle s'adresse aussi bien aux étudiants, aux professionnels ou tout simplement aux curieux technophiles."

[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false